# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN = ./tools/gcc-arm-none-eabi-4_9-2015q3/bin/
PROJECT = MotorBridgeCapeFirmware
OBJECTS = ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/TOOLCHAIN_GCC_ARM/startup_stm32f030x8.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/pwmout_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/serial_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/pinmap.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/sleep.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/us_ticker.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/port_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/gpio_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/mbed_overrides.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/spi_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/gpio_irq_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/analogout_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/i2c_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/analogin_api.o \
	  ./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/PeripheralPins.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_uart_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_smartcard_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_rcc.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_crc.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_rtc_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_gpio.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_pcd.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_dac_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_rcc_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_comp.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_crc_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_smartcard.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_can.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_tsc.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_i2s.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_i2c_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_dma.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_wwdg.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_pwr.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_adc_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_dac.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_tim.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_irda.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_iwdg.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_i2c.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_pcd_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_rtc.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_uart.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_flash.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_spi.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_cortex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_flash_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_tim_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_smbus.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_adc.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_pwr_ex.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_usart.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_cec.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/cmsis_nvic.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/system_stm32f0xx.o \
	  ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/hal_tick.o \
	  ./mbed-src/common/us_ticker_api.o \
	  ./mbed-src/common/semihost_api.o \
	  ./mbed-src/common/lp_ticker_api.o \
	  ./mbed-src/common/error.o \
	  ./mbed-src/common/pinmap_common.o \
	  ./mbed-src/common/gpio.o \
	  ./mbed-src/common/ticker_api.o \
	  ./mbed-src/common/wait_api.o \
	  ./mbed-src/common/rtc_time.o \
	  ./mbed-src/common/board.o \
	  ./mbed-src/common/assert.o \
	  ./mbed-src/common/mbed_interface.o \
	  ./main.o \
	  ./mbed-src/common/InterruptIn.o \
	  ./mbed-src/common/FileSystemLike.o \
	  ./mbed-src/common/I2C.o \
	  ./mbed-src/common/SerialBase.o \
	  ./mbed-src/common/InterruptManager.o \
	  ./mbed-src/common/SPI.o \
	  ./mbed-src/common/FilePath.o \
	  ./mbed-src/common/LocalFileSystem.o \
	  ./mbed-src/common/CAN.o \
	  ./mbed-src/common/TimerEvent.o \
	  ./mbed-src/common/Ticker.o \
	  ./mbed-src/common/Ethernet.o \
	  ./mbed-src/common/SPISlave.o \
	  ./mbed-src/common/FileLike.o \
	  ./mbed-src/common/RawSerial.o \
	  ./mbed-src/common/retarget.o \
	  ./mbed-src/common/Timeout.o \
	  ./mbed-src/common/BusInOut.o \
	  ./mbed-src/common/CallChain.o \
	  ./mbed-src/common/Stream.o \
	  ./mbed-src/common/Serial.o \
	  ./mbed-src/common/FileBase.o \
	  ./mbed-src/common/Timer.o \
	  ./mbed-src/common/BusIn.o \
	  ./mbed-src/common/BusOut.o \
	  ./mbed-src/common/I2CSlave.o \
	  ./mbed-src/3rdparty/Servo/Servo.o \
	  ./mbed-src/3rdparty/SoftPWM/SoftPWM.o \
	  ./mbed-src/3rdparty/SoftServo/SoftServo.o
SYS_OBJECTS = 
INCLUDE_PATHS = -I. -I./mbed-src \
		-I./mbed-src/targets \
		-I./mbed-src/targets/hal \
		-I./mbed-src/targets/hal/TARGET_STM \
		-I./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0 \
		-I./mbed-src/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8 \
		-I./mbed-src/targets/cmsis \
		-I./mbed-src/targets/cmsis/TARGET_STM \
		-I./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0 \
		-I./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8 \
		-I./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/TOOLCHAIN_GCC_ARM \
		-I./mbed-src/common \
		-I./mbed-src/hal \
		-I./mbed-src/api \
		-I./mbed-src/3rdparty/Servo \
		-I./mbed-src/3rdparty/SoftPWM \
		-I./mbed-src/3rdparty/SoftServo 
LIBRARY_PATHS = 
LIBRARIES = 
LINKER_SCRIPT = ./mbed-src/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/TOOLCHAIN_GCC_ARM/STM32F030X8.ld

############################################################################### 
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE    = $(GCC_BIN)arm-none-eabi-size 


CPU = -mcpu=cortex-m0 -mthumb 
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -MMD -MP
CC_SYMBOLS = -DTARGET_NUCLEO_F030R8 -DTARGET_M0 -DTARGET_CORTEX_M -DTARGET_STM -DTARGET_STM32F0 -DTARGET_STM32F030R8 -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -D__CORTEX_M0 -DARM_MATH_CM0 -DMBED_BUILD_TIMESTAMP=1436876371.11 -D__MBED__=1 -DTARGET_FF_ARDUINO -DTARGET_FF_MORPHO 

LD_FLAGS = $(CPU) -Wl,--gc-sections --specs=nano.specs -Wl,--wrap,main -Wl,-Map=$(PROJECT).map,--cref
#LD_FLAGS += -u _printf_float -u _scanf_float
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys


ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif
###################################################
#add your *.cpp *.c file here to compile
#OBJECTS += ./test.o
###################################################

.PHONY: all clean lst size tools

all: tools $(PROJECT).bin $(PROJECT).hex size 


clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(PROJECT).hex $(PROJECT).map $(PROJECT).lst $(OBJECTS) $(DEPS)

tools:
	$(Q)./script/check_tools.sh
.asm.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.s.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.S.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<

.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

.cpp.o: 
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 -fno-rtti $(INCLUDE_PATHS) -o $@ $<



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(OBJCOPY) -O binary $< $@

$(PROJECT).hex: $(PROJECT).elf
	@$(OBJCOPY) -O ihex $< $@

$(PROJECT).lst: $(PROJECT).elf
	@$(OBJDUMP) -Sdh $< > $@

lst: $(PROJECT).lst

size: $(PROJECT).elf
	$(SIZE) $(PROJECT).elf
flash:
	$(Q)./script/flasher $(PROJECT).bin

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)


